#!/bin/bash
#Created by Halil Yavuz Çevik (25/07/2018)

echo -e "ATTENTION! This script collects login informations from:\n\n/var/log/wtmp\n/var/run/btmp\n/var/log/utmp\n\nPlease check if these files exist and check your permissions before you go any further.\n\n"
dayNum=$(date +"%d")
dayStr=$(date +"%a")
month=$(date +"%b")
year=$(date +"%Y")

echo -e "Current Date : $dayStr $month &dayNum &year"
echo -e "Choose a period for login informations:\n 1 - Daily\n 2 - Weekly\n 3 - Monthly"
SCRIPT_DIR=$(pwd)
touch $SCRIPT_DIR/tmp.txt
chmod 755 $SCRIPT_DIR/tmp.txt
HOSTNAME=$(uname -a | cut -d " " -f 2)
echo "$HOSTNAME Login List" >> tmp.txt
echo "===============================================" >> tmp.txt
LOGIN_COUNTER=1
read period
echo "Your Choice: $period"
#Using case construct to eliminate inputs other than 1,2 or 3
case "$period" in

	1)
  		stdbuf -oL utmpdump /var/log/wtmp | grep "$year" | grep "$dayStr $month $dayNum" |
			while IFS= read -r line
			do
				IN="$line"
				arrIN=(${IN//[/[})
				#Lines have whitespaces so we need to use IFS here
				IFS=']'; arrIN=($IN); unset IFS;
				if [ "${arrIN[0]}" = "[7" ];
					then
					#Excluding whitespaces and '[' character
					iflocal="$(echo -e "${arrIN[5]}" | sed -e 's/[[:space:]]*$//' -e 's/^[[:space:]]*//' -e 's/^\[//')"
					iftty="$(echo -e "${arrIN[4]}" | sed -e 's/[[:space:]]*$//' -e 's/^[[:space:]]*//' -e 's/^\[//')"
					#Excluding outputs except physical GUI logins
					if [ "$iflocal" = ":0" ] && [ "$iftty" = "tty1" ]
					
					fi
				fi
			done
  ;;
  
  2)
  
  ;;
  
  3)
  
  ;;
  
  *)
    esco "Please enter a number from list"
esac

vi tmp.txt
rm $SCRIPT_DIR/tmp.txt
